# https://taskfile.dev
version: '2'
tasks:
  install-nodejs:
    desc: install nodejs
    cmds:
      - |
        echo use ASDF to manage multiple versions
        asdf install nodejs 14.3.0
  install-vue-tools:
    cmds:
      - |
        npm install -g @vue/cli
        npm install -g @vue/cli-init
  init:
    cmds:
      - |
        vue init kocal/vue-web-extension new-tab-page
        cd new-tab-page
        npm install
  dev:
    cmds:
      - |
        cd new-tab-page
        npm run watch:dev
  rel-build:
    cmds:
      - |
        cd new-tab-page
        npm run build-zip